$(document).ready(function(){
    $('.slider1').slick({ 
        arrows:true,
        dots:true,
        adaptiveHeigh:true,
        slidesToShow:1,
        slidesToScroll:1,
        speed:500,
        easing:'ease',
        infinite:true,
        autoplaySpeed:1500,
    });    
}); 